services:
  postgres:
    image: postgres:16-alpine
    container_name: findafriend-postgres
    environment:
      POSTGRES_DB: findafriend
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
